#!/bin/sh
. "$(dirname "$0")/_/husky.sh"
# Fix console break on window device
# https://github.com/typicode/husky/issues/968#issuecomment-1176848345
if [ -t 2 ]; then
  exec >/dev/tty 2>&1
fi

pnpm lint-staged --allow-empty --verbose
